# Requires a password to access Redis
requirepass "yM5-lsP7*om2+scL6_ta"

protected-mode yes
loglevel debug
logfile "/var/log/redis.log"
databases 1

# Persistence: AOF (Append Only File)
appendonly yes

# Persistence: RDB snapshot (every 60 sec if 1000+ changes)
save 60 1000

# ACL (Access Control Lists)
# Create user "my_user" with password "my_user_password".
user "lB0ifJ3tuZ" on >"uJ7+osS0%ibK9-taE5@j" ~* &* +@all